### ISSUE TITLE
Improve Create Order UX

### ISSUE THREAD

**Issue by aviggiano** [mousehaunt/mousehaunt.com#31]
# Task update

- [x] Add loading
- [x] Add toaster
- [x] On loading the button must be disabled
- [x]  Not loading created orders
- [x] The users wallet is not clearly connected or disconnected after reload the page.
- [x] After create a new order, the metamask pops up asking if the user allows the access to BMHTL. If the user denies, an error occurs on the console but the page shows success and says that the order was created.
- [x] Fields validation (e.g. negative numbers, etc)

**Comment by karacurt** [comment]
- Fields validation

**Comment by juo-dev** [comment]
- On loading the button must be disabled

**Comment by juo-dev** [comment]
- Error on Load more click
![image](https://user-images.githubusercontent.com/45723253/148387844-4cee8aa5-a40b-4e20-ac14-1c82e80e99b6.png)

**Comment by juo-dev** [comment]
- Not loading created orders

**Comment by juo-dev** [comment]
kkx]lk

![image](https://user-images.githubusercontent.com/45723253/148421647-99487704-2155-4e94-a195-6ce3c05fcdaa.png)

**Comment by pedrohw12** [comment]
The users wallet is not clearly connected or disconnected after reload the page.

After talking to Juliano, we think that the user could stay connected after reload the page, not only in the marketplace, following the pancakeswap and opensea models.

Knowing this, we could improve the UX showing the user his wallet status (connected/disconnected) in a easy and clear way.

**Comment by pedrohw12** [comment]
After create a new order, the metamask pops up asking if the user allows the access to binance. If the user denies, an error occurs on the console but the page shows success and says that the order was created.

<img width="1185" alt="Screen Shot 2022-01-06 at 15 31 19" src="https://user-images.githubusercontent.com/51208665/148432835-67c4bfff-7b1b-490f-b717-d367005d369f.png">

**Comment by juo-dev** [comment]
Released. Marketplace v1.0
